import { json } from '@sveltejs/kit';
import type { RequestHandler } from './$types';
import * as service from '@orvexa/core/service';
import { AppError,type Kind } from '@orvexa/core/contracts';
import { z } from 'zod';
import { pool } from '@orvexa/core/db';
export const GET:RequestHandler=async({params,locals,url})=>{if(params.path==='health')return json({status:'ok'});if(!locals.user)return json({error:'Unauthorized'},{status:401});const [scope,w,resource]=params.path.split('/');try{if(scope!=='workspaces'||!w)return json({error:'Not found'},{status:404});await service.access(locals.user.id,w);if(resource==='events'){const after=z.coerce.number().int().nonnegative().parse(url.searchParams.get('after')??0);return json((await pool.query('SELECT * FROM events WHERE workspace_id=$1 AND id>$2 ORDER BY id LIMIT 100',[w,after])).rows);}return json(await service.loadWorkspace(locals.user.id,w));}catch(e){return handleError(e);}};
const handleError=(e:unknown)=>{if(e instanceof AppError)return json({error:e.message},{status:e.status});if(e instanceof z.ZodError)return json({error:e.issues.map(i=>`${i.path.join('.')}: ${i.message}`).join('; ')},{status:400});console.error('API operation failed',e instanceof Error?e.name:'unknown');return json({error:'Operasi gagal / Operation failed'},{status:500});};
export const POST:RequestHandler=async({params,request,locals,cookies,url})=>{if(request.headers.get('origin')!==url.origin)return json({error:'Invalid origin'},{status:403});if(Number(request.headers.get('content-length')??0)>100000)return json({error:'Payload too large'},{status:413});try{const raw=await request.text();if(raw.length>100000)return json({error:'Payload too large'},{status:413});let body:any;try{body=JSON.parse(raw);}catch{return json({error:'Invalid JSON'},{status:400});}if(params.path==='locale'){const locale=z.enum(['id','en']).parse(body.locale);cookies.set('locale',locale,{path:'/',httpOnly:true,sameSite:'lax',secure:url.protocol==='https:',maxAge:31536000});return json({ok:true});}if(!locals.user)return json({error:'Unauthorized'},{status:401});if(params.path==='workspaces'){const id=await service.createWorkspace(locals.user.id,body);cookies.set('workspace',id,{path:'/',httpOnly:true,sameSite:'lax',secure:url.protocol==='https:'});return json({id},{status:201});}if(params.path==='workspace/select'){await service.access(locals.user.id,body.id);cookies.set('workspace',body.id,{path:'/',httpOnly:true,sameSite:'lax',secure:url.protocol==='https:'});return json({ok:true});}const [scope,w,resource,id,action]=params.path.split('/');if(scope!=='workspaces'||!w)return json({error:'Not found'},{status:404});switch(resource){case 'entities':if(action==='delete'){await service.deleteEntity(locals.user.id,w,id);break;}return json({id:await service.mutateEntity(locals.user.id,w,body.kind as Kind,body.data,id)});case 'profile':await service.updateProfile(locals.user.id,w,body);break;case 'provider':await service.saveProvider(locals.user.id,w,body);break;case 'runs':if(id&&action==='cancel'){await service.cancelRun(locals.user.id,w,id);break;}return json({id:await service.startRun(locals.user.id,w,z.string().uuid().parse(body.taskId))},{status:202});case 'approvals':await service.decide(locals.user.id,w,id,z.enum(['approve','reject']).parse(body.decision));break;default:return json({error:'Not found'},{status:404});}return json({ok:true});}catch(e){return handleError(e);}};
