import {test,expect} from '@playwright/test';
import {randomUUID} from 'node:crypto';
test('owner onboarding, persistent CRUD, bilingual UI and mobile navigation',async({page})=>{
 const failures:string[]=[];page.on('pageerror',e=>failures.push(e.message));
 await page.goto('/register');
 await page.getByLabel('Nama Anda').fill('Test Owner');await page.getByLabel('Email',{exact:true}).fill(`e2e-${randomUUID()}@example.test`);await page.getByLabel('Kata sandi').fill(randomUUID());await page.getByRole('button',{name:'Buat akun',exact:true}).click();
 await expect(page).toHaveURL(/onboarding/);
 await page.getByLabel('Nama perusahaan / usaha').fill('Nusantara Studio');await page.getByLabel('Bidang usaha').fill('Creative services');await page.getByLabel('Ceritakan bisnis Anda').fill('Studio kreatif yang membantu UMKM membangun identitas merek.');await page.getByRole('button',{name:'Buat workspace',exact:true}).click();await expect(page).toHaveURL(/dashboard/);
 await expect(page.getByRole('heading',{name:'Dashboard',exact:true})).toBeVisible();await expect(page.locator('.mini-agent').getByText('Aria',{exact:true})).toBeVisible();
 await page.goto('/knowledge');await page.getByRole('button',{name:'Tambah knowledge',exact:true}).click();await page.getByLabel('Nama',{exact:true}).fill('Layanan & harga');await page.getByLabel('Isi knowledge').fill('Paket identitas merek mulai dari Rp 2.500.000. Konsultasi awal gratis.');await page.getByRole('button',{name:'Simpan',exact:true}).click();await expect(page.getByRole('heading',{name:'Layanan & harga'})).toBeVisible();await page.reload();await expect(page.getByText('Paket identitas merek',{exact:false})).toBeVisible();
 await page.goto('/projects');await page.getByRole('button',{name:'Tambah proyek',exact:true}).click();await page.getByLabel('Nama',{exact:true}).fill('Peluncuran layanan');await page.getByLabel('Deskripsi',{exact:true}).fill('Perkenalkan jasa desain untuk usaha lokal.');await page.getByRole('button',{name:'Simpan',exact:true}).click();await expect(page.getByRole('heading',{name:'Peluncuran layanan'})).toBeVisible();
 await page.goto('/tasks');await page.getByRole('button',{name:'Tambah tugas',exact:true}).click();await page.getByLabel('Nama',{exact:true}).fill('Susun rencana pemasaran');await page.getByLabel('Deskripsi',{exact:true}).fill('Buat rencana promosi selama satu minggu berdasarkan knowledge perusahaan.');await page.getByRole('combobox',{name:'Karyawan AI',exact:true}).selectOption({label:'Aria · Business Coordinator'});await page.getByRole('combobox',{name:'Proyek',exact:true}).selectOption({label:'Peluncuran layanan'});await page.getByRole('button',{name:'Simpan',exact:true}).click();await expect(page.getByRole('heading',{name:'Susun rencana pemasaran'})).toBeVisible();await page.getByRole('button',{name:'Jalankan',exact:true}).click();await expect(page.getByRole('alert')).toContainText('Hubungkan AI provider');
 await page.getByLabel('Status tugas').selectOption('in_progress');await expect(page.locator('.kanban-column').nth(1).getByRole('heading',{name:'Susun rencana pemasaran'})).toBeVisible();
 await page.getByRole('button',{name:'Switch language / Ganti bahasa'}).click();await expect(page.getByRole('heading',{name:'Tasks',exact:true})).toBeVisible();await page.reload();await expect(page.getByRole('heading',{name:'Tasks',exact:true})).toBeVisible();
 for(const section of ['dashboard','agents','divisions','company','rooms','approvals','virtual-office','activity','providers','usage','settings']){await page.goto('/'+section);await expect(page.locator('main h1')).toBeVisible();await expect(page.locator('body')).not.toContainText('Internal Error');}
 await page.goto('/dashboard');await page.screenshot({path:'test-results/dashboard-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'Open navigation'}).click();await page.locator('nav').getByRole('link',{name:'Business Profile',exact:true}).click();await expect(page.getByRole('heading',{name:'Business Profile',exact:true})).toBeVisible();await expect(page.locator('.sidebar')).not.toHaveClass(/mobile-open/);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true);await page.screenshot({path:'test-results/company-mobile.png',fullPage:true});
 await page.goto('/dashboard');await page.getByRole('button',{name:'New task',exact:true}).click();await expect(page.getByRole('dialog')).toBeVisible();await page.keyboard.press('Escape');await expect(page.getByRole('dialog')).not.toBeVisible();
 expect(failures).toEqual([]);
});
