<script lang="ts">
import {page} from '$app/state';import {invalidate} from '$app/navigation';import {goto,invalidateAll} from '$app/navigation';import {useLocale} from '$lib/i18n';import Language from '$lib/components/Language.svelte';import {post} from '$lib/api';import {LayoutDashboard,MessagesSquare,FolderKanban,ListTodo,ShieldCheck,Users,Bot,Building2,BookOpen,Activity,Settings,Plug,Zap,Menu,ChevronDown,Plus,LogOut,ArrowUpRight} from 'lucide-svelte';
let {data,children}=$props();const {t}=useLocale();let mobile=$state(false);
const groups:{id:string;en:string;items:[string,typeof LayoutDashboard,string,string][]}[]=[{id:'WORKSPACE',en:'WORKSPACE',items:[['dashboard',LayoutDashboard,'Dashboard','Dashboard'],['rooms',MessagesSquare,'Rooms','Rooms'],['projects',FolderKanban,'Proyek','Projects'],['tasks',ListTodo,'Tugas','Tasks'],['approvals',ShieldCheck,'Persetujuan','Approvals']]},{id:'TIM AI',en:'AI WORKFORCE',items:[['agents',Bot,'Karyawan AI','AI Employees'],['divisions',Users,'Divisi','Divisions'],['virtual-office',Building2,'Virtual Office','Virtual Office']]},{id:'PERUSAHAAN',en:'COMPANY',items:[['company',Building2,'Profil Bisnis','Business Profile'],['knowledge',BookOpen,'Knowledge','Knowledge'],['activity',Activity,'Aktivitas','Activity']]},{id:'SISTEM',en:'SYSTEM',items:[['providers',Plug,'AI Provider','AI Provider'],['usage',Zap,'Penggunaan AI','AI Usage'],['settings',Settings,'Pengaturan','Settings']]}];
$effect(()=>{const id=data.workspace.id;const after=data.events[0]?.id??0;const stream=new EventSource(`/api/workspaces/${id}/stream?after=${after}`);stream.onmessage=()=>{void invalidate('app:data');};return()=>stream.close();});
async function logout(){await fetch('/api/auth/sign-out',{method:'POST',headers:{'Content-Type':'application/json'},body:'{}'});await goto('/login',{invalidateAll:true});}
async function switchWorkspace(e:Event){await post('workspace/select',{id:(e.target as HTMLSelectElement).value});await invalidateAll();}
</script>
<div class="app-shell">{#if mobile}<button class="sidebar-scrim" aria-label="Close navigation" onclick={()=>mobile=false}></button>{/if}<aside class:mobile-open={mobile} class="sidebar"><a class="brand" href="/dashboard"><img src="/favicon.svg" alt=""/><div>ORVEXA<small>Your AI Workforce.</small></div></a><div class="workspace-switch"><span class="workspace-avatar">{data.workspace.name.slice(0,1)}</span><div><small>WORKSPACE</small><select aria-label={t('Pilih perusahaan','Select company')} value={data.workspace.id} onchange={switchWorkspace}>{#each data.choices as choice}<option value={choice.id}>{choice.name}</option>{/each}</select></div></div><nav>{#each groups as group}<div class="nav-group"><p>{t(group.id,group.en)}</p>{#each group.items as item}{@const Icon=item[1]}<a class:active={page.url.pathname===`/${item[0]}`} href={`/${item[0]}`} onclick={()=>mobile=false}><Icon size={18} strokeWidth={1.7}/><span>{t(item[2] as string,item[3] as string)}</span>{#if item[0]==='virtual-office'}<span class="nav-badge">BETA</span>{/if}{#if item[0]==='approvals'&&data.approvals.filter(a=>a.status==='pending').length}<b class="count">{data.approvals.filter(a=>a.status==='pending').length}</b>{/if}</a>{/each}</div>{/each}</nav><div class="sidebar-bottom"><div class="avatar owner">{data.user.name.slice(0,1)}</div><div><strong>{data.user.name}</strong><small>{t('Pemilik bisnis','Business owner')}</small></div><button class="icon-btn" onclick={logout} aria-label={t('Keluar','Sign out')} title={t('Keluar','Sign out')}><LogOut size={17}/></button></div></aside><div class="app-main"><header class="topbar"><div class="breadcrumb"><button class="icon-btn mobile-menu" onclick={()=>mobile=true} aria-label="Open navigation"><Menu size={21}/></button><span>{data.workspace.name}</span><span>/</span><strong>{t('Ruang kerja','Workspace')}</strong></div><div class="topbar-actions"><span class="connection"><i></i>{t('Workspace aktif','Workspace active')}</span><Language/><span class="topbar-divider"></span><div class="avatar owner">{data.user.name.slice(0,1)}</div></div></header><main>{@render children()}</main><footer class="app-footer"><span>ORVEXA · {t('Tim AI untuk usaha Anda','Your business. Your AI team.')}</span><span>{t('Anda tetap memegang kendali','You stay in control')}</span></footer></div></div>
