import {test,expect,beforeAll,afterAll} from 'bun:test';
import {pool,uid} from '../packages/core/src/db';
import {createWorkspace,mutateEntity,loadWorkspace,saveProvider,startRun,access,cancelRun,decide,deleteEntity,updateProfile} from '../packages/core/src/service';
import {executeRun} from '../packages/core/src/runner';
import {Queue,Worker,QueueEvents} from 'bullmq';
const owner=uid(),other=uid();let workspace:string,foreign:string,agent:string,task:string;const runIds:string[]=[];let calls=0;
const profile={name:'Integration test company',industry:'Testing',description:'Private company context',website:'',language:'en',timezone:'Asia/Jakarta',autonomous:true,paused:false};
const mockModel=async()=>{calls++;return {text:`Verified test contribution ${calls}`,inputTokens:15,outputTokens:10};};
async function makeRun(approval=false){const taskId=await mutateEntity(owner,workspace,'task',{name:'Integration objective',agentId:agent,requiresApproval:approval});const id=await startRun(owner,workspace,taskId);runIds.push(id);return id;}
beforeAll(async()=>{await pool.query('INSERT INTO "user"(id,name,email) VALUES($1,$2,$3),($4,$2,$5)',[owner,'Test owner',`${owner}@example.test`,other,`${other}@example.test`]);workspace=await createWorkspace(owner,profile);foreign=await createWorkspace(other,{...profile,name:'Isolated company'});agent=await mutateEntity(owner,workspace,'agent',{name:'Coordinator',role:'Coordinator'});await mutateEntity(owner,workspace,'agent',{name:'Specialist',role:'Marketing specialist'});task=await mutateEntity(owner,workspace,'task',{name:'First objective',agentId:agent});});
afterAll(async()=>{for(const id of runIds){for(const table of ['checkpoint_writes','checkpoint_blobs','checkpoints'])await pool.query(`DELETE FROM ${table} WHERE thread_id=$1`,[id]);}for(const w of [workspace,foreign]){await pool.query('DELETE FROM model_steps WHERE run_id IN (SELECT id FROM runs WHERE workspace_id=$1)',[w]);await pool.query('DELETE FROM outbox WHERE run_id IN (SELECT id FROM runs WHERE workspace_id=$1)',[w]);for(const table of ['task_schedules','approvals','events','runs','providers','entities','memberships'])await pool.query(`DELETE FROM ${table} WHERE workspace_id=$1`,[w]);await pool.query('DELETE FROM workspaces WHERE id=$1',[w]);}await pool.query('DELETE FROM "user" WHERE id=ANY($1)',[[owner,other]]);await pool.end();});
test('workspace isolation rejects reads and cross-tenant references',async()=>{await expect(access(other,workspace)).rejects.toThrow();const foreignAgent=await mutateEntity(other,foreign,'agent',{name:'Private employee',role:'Analyst'});await expect(mutateEntity(owner,workspace,'task',{name:'Cross tenant task',agentId:foreignAgent})).rejects.toThrow();});
test('published knowledge persists and resource deletion checks references',async()=>{const id=await mutateEntity(owner,workspace,'knowledge',{name:'Pricing policy',content:'Use published prices only.'});const state=await loadWorkspace(owner,workspace);expect(state.entities.find(e=>e.id===id)?.data.content).toBe('Use published prices only.');await expect(deleteEntity(owner,workspace,agent)).rejects.toThrow();});
test('provider required, secret never exposed, concurrent start deduplicates',async()=>{await expect(startRun(owner,workspace,task)).rejects.toThrow();await saveProvider(owner,workspace,{model:'test-model',apiKey:'integration-fake-key'});expect(JSON.stringify((await loadWorkspace(owner,workspace)).provider)).not.toContain('integration-fake-key');const ids=await Promise.all([startRun(owner,workspace,task),startRun(owner,workspace,task)]);expect(ids[0]).toBe(ids[1]);runIds.push(ids[0]);await cancelRun(owner,workspace,ids[0]);});
test('multi-agent graph persists results and never replays completed run',async()=>{calls=0;const id=await makeRun();await executeRun(id,mockModel);let r=(await pool.query('SELECT * FROM runs WHERE id=$1',[id])).rows[0];expect(r.error_code).toBeNull();expect(r.status).toBe('succeeded');expect(r.result).toContain('Verified test contribution');expect(calls).toBe(3);expect(r.input_tokens).toBe(45);await executeRun(id,mockModel);expect(calls).toBe(3);},30000);
test('approval interrupts across graph instances then resumes once',async()=>{calls=0;const id=await makeRun(true);await executeRun(id,mockModel);expect(calls).toBe(0);expect((await pool.query('SELECT status FROM runs WHERE id=$1',[id])).rows[0].status).toBe('waiting_approval');const approval=(await pool.query('SELECT id FROM approvals WHERE run_id=$1',[id])).rows[0];await decide(owner,workspace,approval.id,'approve');await expect(decide(owner,workspace,approval.id,'approve')).rejects.toThrow();await executeRun(id,mockModel);expect((await pool.query('SELECT status FROM runs WHERE id=$1',[id])).rows[0].status).toBe('succeeded');expect(calls).toBe(3);},30000);
test('cancelled run invokes no model',async()=>{calls=0;const id=await makeRun();await cancelRun(owner,workspace,id);await executeRun(id,mockModel);expect(calls).toBe(0);});
test('pause prevents new work',async()=>{await updateProfile(owner,workspace,{...profile,paused:true});await expect(makeRun()).rejects.toThrow();await updateProfile(owner,workspace,profile);});
test('BullMQ on Redis dispatches a persistent run',async()=>{const url=new URL(process.env.REDIS_URL!);const connection={host:url.hostname,port:Number(url.port),maxRetriesPerRequest:null};const name=`test-${uid()}`,queue=new Queue(name,{connection}),events=new QueueEvents(name,{connection}),worker=new Worker(name,async job=>executeRun(job.data.runId,mockModel),{connection});await events.waitUntilReady();try{const id=await makeRun();const job=await queue.add('run',{runId:id});await job.waitUntilFinished(events,20000);expect((await pool.query('SELECT status FROM runs WHERE id=$1',[id])).rows[0].status).toBe('succeeded');}finally{await worker.close();await events.close();await queue.obliterate({force:true});await queue.close();}},30000);

test('scheduled occurrence is atomic and repeated ticks do not create extra work',async()=>{const id=await mutateEntity(owner,workspace,'task',{name:'Recurring objective',agentId:agent,schedule:'daily'});expect(await startRun(owner,workspace,id,true)).toBeNull();await pool.query("UPDATE task_schedules SET next_at=now()-interval '1 minute' WHERE task_id=$1",[id]);const runs=await Promise.all([startRun(owner,workspace,id,true),startRun(owner,workspace,id,true)]);const actual=runs.filter(Boolean) as string[];runIds.push(...actual);expect(actual.length).toBe(1);expect(runs.includes(null)).toBe(true);await cancelRun(owner,workspace,actual[0]);});
