import { pool,db,entities,uid } from './db';
import { eq } from 'drizzle-orm';
import { AppError,allowed,schemas,profileSchema,type Kind } from './contracts';
import { encrypt } from './crypto';
import { z } from 'zod';
import type { PoolClient } from 'pg';
export async function access(userId:string,workspaceId:string,operation:'read'|'write'|'admin'='read') {
 const {rows}=await pool.query('SELECT role FROM memberships WHERE user_id=$1 AND workspace_id=$2',[userId,workspaceId]);
 if(!rows[0])throw new AppError(404,'Workspace tidak ditemukan / Workspace not found');
 if(!allowed(rows[0].role,operation))throw new AppError(403,'Akses ditolak / Access denied');
 return rows[0].role as string;
}
export async function transaction<T>(fn:(c:PoolClient)=>Promise<T>){const c=await pool.connect();try{await c.query('BEGIN');const result=await fn(c);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
export async function event(c:PoolClient|typeof pool,w:string,actor:string,kind:string,message:string,runId:string|null=null){await c.query('INSERT INTO events(workspace_id,actor,kind,message,run_id) VALUES($1,$2,$3,$4,$5)',[w,actor,kind,message,runId]);}
export async function createWorkspace(userId:string,input:unknown){const profile=profileSchema.parse(input),id=uid();await transaction(async c=>{await c.query('INSERT INTO workspaces(id,name,owner_id,profile) VALUES($1,$2,$3,$4)',[id,profile.name,userId,profile]);await c.query("INSERT INTO memberships VALUES($1,$2,'owner')",[id,userId]);for(const [name,color]of [['Operations','blue'],['Marketing','purple'],['Sales','green'],['Finance','orange']])await c.query('INSERT INTO entities(id,workspace_id,kind,data) VALUES($1,$2,$3,$4)',[uid(),id,'division',{name,color,description:''}]);await event(c,id,'Owner','company.created',profile.name);});return id;}
export async function loadWorkspace(userId:string,w:string){const role=await access(userId,w);const [workspace,allEntities,runs,events,approvals,provider,members]=await Promise.all([pool.query('SELECT * FROM workspaces WHERE id=$1',[w]),db.select().from(entities).where(eq(entities.workspaceId,w)),pool.query('SELECT id,task_id,status,result,error_code,input_tokens,output_tokens,created_at,updated_at FROM runs WHERE workspace_id=$1 ORDER BY created_at DESC LIMIT 100',[w]),pool.query('SELECT * FROM events WHERE workspace_id=$1 ORDER BY id DESC LIMIT 100',[w]),pool.query('SELECT * FROM approvals WHERE workspace_id=$1 ORDER BY created_at DESC LIMIT 100',[w]),pool.query('SELECT model,updated_at FROM providers WHERE workspace_id=$1',[w]),pool.query('SELECT u.name,u.email,m.role FROM memberships m JOIN "user" u ON u.id=m.user_id WHERE m.workspace_id=$1',[w])]);return {workspace:workspace.rows[0],role,entities:allEntities.map(e=>({...e,workspace_id:e.workspaceId,created_at:e.createdAt.toISOString(),updated_at:e.updatedAt.toISOString()})),runs:runs.rows,events:events.rows,approvals:approvals.rows,provider:provider.rows[0]??null,members:members.rows};}
export async function mutateEntity(userId:string,w:string,kind:Kind,input:unknown,id?:string){if(!Object.hasOwn(schemas,kind))throw new AppError(400,'Invalid entity');await access(userId,w,['agent','division','knowledge'].includes(kind)?'admin':'write');const data=schemas[kind].parse(input);const entityId=id?z.string().uuid().parse(id):uid();return transaction(async c=>{await c.query('SELECT id FROM workspaces WHERE id=$1 FOR UPDATE',[w]);for(const [key,expected]of [['divisionId','division'],['projectId','project'],['agentId','agent']]){const ref=(data as any)[key];if(ref){const {rows}=await c.query('SELECT id FROM entities WHERE id=$1 AND workspace_id=$2 AND kind=$3',[ref,w,expected]);if(!rows[0])throw new AppError(400,'Referensi tidak valid / Invalid reference');}}if(id){const result=await c.query('UPDATE entities SET data=$1,updated_at=now() WHERE id=$2 AND workspace_id=$3 AND kind=$4 RETURNING id',[data,id,w,kind]);if(!result.rowCount)throw new AppError(404,'Not found');}else await c.query('INSERT INTO entities(id,workspace_id,kind,data) VALUES($1,$2,$3,$4)',[entityId,w,kind,data]);if(kind==='task'){const cadence=(data as any).schedule;if(cadence==='none')await c.query('DELETE FROM task_schedules WHERE task_id=$1',[entityId]);else await c.query("INSERT INTO task_schedules(task_id,workspace_id,created_by,cadence,next_at) VALUES($1,$2,$3,$4,now()+$5::interval) ON CONFLICT(task_id) DO UPDATE SET cadence=$4,next_at=CASE WHEN task_schedules.cadence=$4 THEN task_schedules.next_at ELSE now()+$5::interval END",[entityId,w,userId,cadence,cadence==='daily'?'24 hours':'168 hours']);}await event(c,w,'Owner',`${kind}.${id?'updated':'created'}`,data.name);return entityId;});}
export async function deleteEntity(userId:string,w:string,id:string){await access(userId,w,'admin');await transaction(async c=>{await c.query('SELECT id FROM workspaces WHERE id=$1 FOR UPDATE',[w]);const references=await c.query("SELECT id FROM entities WHERE workspace_id=$1 AND (data->>'divisionId'=$2 OR data->>'projectId'=$2 OR data->>'agentId'=$2) UNION SELECT id FROM runs WHERE workspace_id=$1 AND task_id=$2 LIMIT 1",[w,id]);if(references.rowCount)throw new AppError(409,'Masih digunakan / Still in use');const result=await c.query('DELETE FROM entities WHERE id=$1 AND workspace_id=$2 RETURNING data',[id,w]);if(!result.rowCount)throw new AppError(404,'Not found');await event(c,w,'Owner','entity.deleted',result.rows[0].data.name);});}
export async function updateProfile(userId:string,w:string,input:unknown){await access(userId,w,'admin');const data=profileSchema.parse(input);await transaction(async c=>{await c.query('UPDATE workspaces SET name=$1,profile=$2 WHERE id=$3',[data.name,data,w]);await event(c,w,'Owner','company.updated',data.name);});}
export async function saveProvider(userId:string,w:string,input:unknown){await access(userId,w,'admin');const {model,apiKey}=z.object({model:z.string().trim().min(1).max(100),apiKey:z.string().trim().min(10).max(500)}).parse(input);await pool.query('INSERT INTO providers(workspace_id,model,secret) VALUES($1,$2,$3) ON CONFLICT(workspace_id) DO UPDATE SET model=$2,secret=$3,updated_at=now()',[w,model,encrypt(apiKey)]);await event(pool,w,'Owner','provider.updated',model);}
export async function startRun(userId:string,w:string,taskId:string,scheduled=false){await access(userId,w,'write');return transaction(async c=>{await c.query('SELECT id FROM workspaces WHERE id=$1 FOR UPDATE',[w]);const company=(await c.query('SELECT * FROM workspaces WHERE id=$1',[w])).rows[0];if(company.profile.paused)throw new AppError(409,'Operasi dijeda / Operations paused');const provider=(await c.query('SELECT model FROM providers WHERE workspace_id=$1',[w])).rows[0];if(!provider)throw new AppError(409,'Hubungkan AI provider terlebih dahulu / Connect an AI provider first');const task=(await c.query("SELECT * FROM entities WHERE workspace_id=$1 AND id=$2 AND kind='task'",[w,taskId])).rows[0];if(!task)throw new AppError(404,'Task not found');const agent=(await c.query("SELECT * FROM entities WHERE workspace_id=$1 AND id=$2 AND kind='agent'",[w,task.data.agentId])).rows[0];if(!agent||agent.data.status!=='active')throw new AppError(409,'Pilih karyawan AI aktif / Assign an active AI employee');if(scheduled){const schedule=(await c.query('SELECT * FROM task_schedules WHERE task_id=$1 AND workspace_id=$2 AND next_at<=now() FOR UPDATE',[taskId,w])).rows[0];if(!schedule)return null;await c.query('UPDATE task_schedules SET next_at=now()+$1::interval WHERE task_id=$2',[schedule.cadence==='daily'?'24 hours':'168 hours',taskId]);}const active=(await c.query("SELECT id FROM runs WHERE task_id=$1 AND status IN ('queued','running','waiting_approval')",[taskId])).rows[0];if(active)return active.id;const knowledge=(await c.query("SELECT id,data FROM entities WHERE workspace_id=$1 AND kind='knowledge' AND data->>'status'='published' ORDER BY created_at DESC LIMIT 12",[w])).rows;const specialists=(await c.query("SELECT id,data FROM entities WHERE workspace_id=$1 AND kind='agent' AND data->>'status'='active' AND id<>$2 ORDER BY created_at LIMIT 2",[w,agent.id])).rows;const id=uid();await c.query('INSERT INTO runs(id,workspace_id,task_id,status,snapshot) VALUES($1,$2,$3,$4,$5)',[id,w,taskId,'queued',{company:company.profile,task:task.data,agent:agent.data,specialists,knowledge,model:provider.model,version:1}]);await c.query('INSERT INTO outbox(id,run_id) VALUES($1,$2)',[uid(),id]);await event(c,w,agent.data.name,'run.queued',task.data.name,id);return id;});}
export async function cancelRun(userId:string,w:string,id:string){await access(userId,w,'write');await transaction(async c=>{const result=await c.query("UPDATE runs SET cancel_requested=true,status='cancelled',updated_at=now() WHERE id=$1 AND workspace_id=$2 AND status IN ('queued','running','waiting_approval') RETURNING id",[id,w]);if(!result.rowCount)throw new AppError(409,'Run tidak aktif / Run is not active');await c.query("UPDATE approvals SET status='rejected',decided_by=$1 WHERE run_id=$2 AND status='pending'",[userId,id]);await event(c,w,'Owner','run.cancelled','Pekerjaan dibatalkan / Run cancelled',id);});}
export async function decide(userId:string,w:string,id:string,decision:'approve'|'reject'){await access(userId,w,'admin');await transaction(async c=>{const a=(await c.query('SELECT * FROM approvals WHERE id=$1 AND workspace_id=$2 FOR UPDATE',[id,w])).rows[0];if(!a)throw new AppError(404,'Not found');if(a.status!=='pending')throw new AppError(409,'Keputusan sudah tercatat / Decision already recorded');if(new Date(a.expires_at)<new Date())throw new AppError(409,'Persetujuan kedaluwarsa / Approval expired');const run=(await c.query('SELECT status FROM runs WHERE id=$1 FOR UPDATE',[a.run_id])).rows[0];if(run.status!=='waiting_approval')throw new AppError(409,'Run is not waiting for approval');await c.query('UPDATE approvals SET status=$1,decided_by=$2 WHERE id=$3',[decision==='approve'?'approved':'rejected',userId,id]);await c.query('UPDATE runs SET status=$1,updated_at=now() WHERE id=$2',[decision==='approve'?'queued':'cancelled',a.run_id]);if(decision==='approve')await c.query('INSERT INTO outbox(id,run_id) VALUES($1,$2)',[uid(),a.run_id]);await event(c,w,'Owner',`approval.${decision}`,decision,a.run_id);});}
