import { pool } from '../packages/core/src/db';
const origin=process.env.VERIFY_ORIGIN??process.env.APP_ORIGIN??'http://localhost:5173';
const email=`idem-${crypto.randomUUID()}@example.test`;
const password=crypto.randomUUID()+crypto.randomUUID();
const cookies=new Map<string,string>();
async function api(path:string,body:unknown,headers:Record<string,string>={}) {
	const requestHeaders:Record<string,string>={'Content-Type':'application/json',origin,...headers};
	if(cookies.size)requestHeaders.cookie=[...cookies.values()].join('; ');
	const response=await fetch(`${origin}/api/${path}`,{method:'POST',headers:requestHeaders,body:JSON.stringify(body)});
	const raw=response.headers.getSetCookie?.()??[];
	for(const value of raw){const pair=value.split(';')[0];const separator=pair.indexOf('=');if(separator>0)cookies.set(pair.slice(0,separator),pair);}
	return response;
}
const signup=await api('auth/sign-up/email',{name:'Idem Check',email,password});
if(!signup.ok)throw new Error(`signup failed: ${signup.status} ${await signup.text()}`);
const workspace=(await (await api('workspaces',{name:'Idem Verify',industry:'Testing',description:'HTTP idempotency verification',website:'',language:'id',timezone:'Asia/Jakarta',autonomous:true,paused:false})).json()).id as string;
const agent=(await (await api(`workspaces/${workspace}/entities`,{kind:'agent',data:{name:'Aria',role:'Coordinator'}})).json()).id as string;
const task=(await (await api(`workspaces/${workspace}/entities`,{kind:'task',data:{name:'Objek idem',agentId:agent}})).json()).id as string;
const provider=await api(`workspaces/${workspace}/provider`,{model:'test-model',apiKey:'verification-key-123'});
if(!provider.ok)throw new Error(`provider failed: ${provider.status}`);
const run=async(key?:string)=>await api(`workspaces/${workspace}/runs`,{taskId:task},key?{'Idempotency-Key':key}:{});
const expect=(cond:boolean,label:string)=>{if(!cond)throw new Error(`FAIL: ${label}`);console.log(`pass: ${label}`);};
const key=crypto.randomUUID();
const first=await run(key);
expect(first.status===202,'202 Created pada start run');
const firstBody=await first.json() as {id:string};
expect(first.headers.get('idempotency-key')===key,'response header Idempotency-Key echo');
expect(first.headers.get('location')===`/api/workspaces/${workspace}/runs/${firstBody.id}`,'header Location menuju run');
const r1=firstBody.id;
const second=await run(key);
const secondBody=await second.json() as {id:string};
expect(secondBody.id===r1,'replay key yang sama mengembalikan run yang sama');
expect(second.headers.get('idempotency-key')===key,'replay tetap meng-echo header');
const keyless=await run();
expect((await keyless.json()).id===r1,'tanpa key: dedupe run aktif per task');
await api(`workspaces/${workspace}/runs/${r1}/cancel`,{});
const replayTerminal=await run(key);
expect((await replayTerminal.json()).id===r1,'run terminal tetap di-replay dengan key sama');
const fresh=await run();
const r2=(await fresh.json()).id as string;
expect(r2!==r1,'run baru tanpa key setelah run sebelumnya terminal');
await api(`workspaces/${workspace}/runs/${r2}/cancel`,{});
const forRun=await pool.query('SELECT idempotency_key FROM runs WHERE id=$1',[r1]);
expect(forRun.rows[0]?.idempotency_key===key,'key tersimpan pada run di database');
for(const table of ['model_steps','outbox'])await pool.query(`DELETE FROM ${table} WHERE run_id IN (SELECT id FROM runs WHERE workspace_id=$1)`,[workspace]);
for(const table of ['approvals','events','runs'])await pool.query(`DELETE FROM ${table} WHERE workspace_id=$1`,[workspace]);
await pool.query('DELETE FROM task_schedules WHERE task_id IN (SELECT id FROM entities WHERE workspace_id=$1)',[workspace]);
for(const table of ['entities','memberships'])await pool.query(`DELETE FROM ${table} WHERE workspace_id=$1`,[workspace]);
await pool.query('DELETE FROM providers WHERE workspace_id=$1',[workspace]);
await pool.query('DELETE FROM workspaces WHERE id=$1',[workspace]);
await pool.query('DELETE FROM "user" WHERE email=$1',[email]);
await pool.end();
console.log('Idempotency HTTP verification passed.');
